import Head from "next/head";
import { FC } from "react";
import Header from "./Header";

interface Props {
  children: React.ReactNode;
}

const Layout: FC<Props> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col h-screen relative bg-gray-200">
        <Header />
        <div className="flex-grow">{children}</div>
      </div>
    </>
  );
};

export default Layout;
